### ISSUE TITLE
missing AndroidManifest.xml when building

### ISSUE THREAD

**Issue by Pitoum** [SempaiGames/openfl-gps-lib#2]
Android target : 19
I don't really know which other information could be relevant.

**BUILD FAILED**
```
E:\Development\Android SDK\tools\ant\build.xml:577: com.android.io.StreamException: java.io.FileNotFoundException: E:\PROJETS\Tarmac\TMM\bin\android\bin\deps\google-play-services_lib\AndroidManifest.xml (Le fichier spécifié est introuvable)
    at com.android.io.FileWrapper.getContents(FileWrapper.java:93)
    at com.android.xml.AndroidManifest.getStringValue(AndroidManifest.java:410)
    at com.android.xml.AndroidManifest.getPackage(AndroidManifest.java:146)
    at com.android.ant.ComputeDependencyTask$1.processLibrary(ComputeDependencyTask.java:198)
    at com.android.ant.DependencyHelper$AdvancedLibraryProcessor.processLibrary(DependencyHelper.java:69)
    at com.android.ant.DependencyHelper.processLibraries(DependencyHelper.java:210)
    at com.android.ant.GetLibraryPathTask.execute(GetLibraryPathTask.java:183)
    at com.android.ant.GetLibraryPathTask.execute(GetLibraryPathTask.java:162)
    at com.android.ant.ComputeDependencyTask.execute(ComputeDependencyTask.java:226)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
    at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.Main.runBuild(Main.java:851)
    at org.apache.tools.ant.Main.startAnt(Main.java:235)
    at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
    at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.io.FileNotFoundException: E:\PROJETS\Tarmac\TMM\bin\android\bin\deps\google-play-services_lib\AndroidManifest.xml (Le fichier spécifié est introuvable)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:120)
    at com.android.io.FileWrapper.getContents(FileWrapper.java:91)
    ... 24 more
```
Total time: 0 seconds
Build halted with errors.

**Comment by fbricker** [comment]
Hi, did you downloaded google play services from your android package manager (see: https://github.com/SempaiGames/openfl-gpg#how-to-install)

Also, make sure you're using openfl-legacy (since openfl-next does not support android extensions using JNI yet).

**Comment by Pitoum** [comment]
I do have google play services downloaded.
I'll look into the all legacy/next suggestion monday (it's on my work computer).
Thanks!

**Comment by Pitoum** [comment]
Hi again,

So far no change.
I'll try to give you as much information I can.

These are my libraries installed and there versions:
actuate: [1.8.6]
extension-nativedialog: [1.2.1]
ganalytics: [0.0.3]
HaxePunk: 2.5.5 [2.5.6]
hxcpp: [3.2.102]
lime-samples: 2.3.0 [2.5.1]
lime: 2.4.3 2.4.5 [2.5.2]
**openfl-gpg: [1.3.0]**
**openfl-gps-lib: 1.0.3 [1.0.4]**
openfl-ouya: [1.0.2]
openfl-unityads: [1.0.3]
**openfl: 3.1.1 [3.2.2]**

These are the installed packages:
[![Gyazo](https://i.gyazo.com/39488e8f4d9f8611a7ea0b6eb1e12e0a.png)](https://gyazo.com/39488e8f4d9f8611a7ea0b6eb1e12e0a)

These are the files in my bin folder for my haxepunk project:
[![Gyazo](https://i.gyazo.com/57a18e020193f82a4a4ac5c9ba54d101.png)](https://gyazo.com/57a18e020193f82a4a4ac5c9ba54d101)

This is my project.xml:
<?xml version="1.0" encoding="utf-8"?>
<project>
	<meta title="Hareport - Crazy flights" package="com.teamto.*********" version-code="2" version="0.1.3" company="TeamTO Games" />

 	<app file="Hareport - Crazy flights" main="Main" path="bin" />
	
	<certificate path="**********" alias="*********" password="*******" if="android" unless="debug"/>
	
	<window fps="60" background="0x333333" />
	<window width="960" height="540" resizable="true" unless="mobile" />
	<window fullscreen="true" if="mobile" />
	<window orientation="landscape" vsync="true" antialiasing="0" if="cpp" />

	<source path="src" />

	<haxelib name="HaxePunk" />
	<haxelib name="Actuate" />
	<haxelib name="openfl-unityads" />
	<haxelib name="ganalytics" />
	<haxelib name="openfl-gps-lib" />
	<haxelib name="openfl-gpg" />
	<haxelib name="extension-nativedialog" />
	
	<assets path="assets/shaders" rename="shaders" include="*.vert|*.frag" />
	<assets path="assets/graphics" rename="graphics" include="*.png|*.jpg" />
	<assets path="assets/audio" rename="audio" include="*.mp3" if="flash" />
	<assets path="assets/audio" rename="audio" include="*.wav|*.ogg" unless="flash" />
	<assets path="assets/font" rename="font" include="*.ttf" />

	<setenv name="GOOGLE_PLAY_GAMES_ID" value="************" />
	
	<set name="openfl-legacy" />
	
	<android target-sdk-version="19" />
	
	<icon path="assets/HaxePunk.svg" />
</project>

And I'm not sure what I can add :\

**Comment by fbricker** [comment]
Hi, just in case: Can you check that the SDK you're using to download the Google Play Services Lib is the same that OpenFL is using to build the project?

Another option is to manually add the required files to your project: In your case, you should be able to copy the files in "E:\Development\Android SDK\extras/google/google_play_services/libproject/google-play-services_lib" to your "bin/android/bin/deps/google-play-services_lib".

**Comment by Pitoum** [comment]
...
I'm so sorry.
I want to die -_-
Thanks to make me realize I had an old sdk folder.

**Comment by fbricker** [comment]
Never mind :) Glad you fixed it!
